import com.android.build.api.artifact.ScopedArtifact
import com.android.build.api.artifact.SingleArtifact
import com.android.build.api.variant.DeviceTestBuilder
import com.android.build.api.variant.ScopedArtifacts
import java.util.Properties
import java.util.zip.ZipFile
import org.gradle.api.artifacts.result.ResolvedComponentResult
import org.gradle.api.artifacts.result.ResolvedDependencyResult

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.compose.compiler)
}

// Machine-specific settings live in the gitignored local.properties, never in the repo:
//   fineprint.bundleUrl=http://<host>:8080/   (debug bundle server; default: the emulator's host loopback)
//   fineprint.cleartextHost=<host>            (extra host allowed over plain HTTP in debug, e.g. a Tailscale name)
val localProps = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use { load(it) }
}
val debugBundleUrl = localProps.getProperty("fineprint.bundleUrl") ?: "http://10.0.2.2:8080/"
val debugCleartextHost = localProps.getProperty("fineprint.cleartextHost").orEmpty()

android {
    namespace = "com.longlifeio.fineprint"
    compileSdk = 37

    defaultConfig {
        applicationId = "com.longlifeio.fineprint"
        minSdk = 29
        targetSdk = 37
        versionCode = 1
        versionName = "0.2.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            buildConfigField("String", "BUNDLE_BASE_URL", "\"$debugBundleUrl\"")
        }
        release {
            buildConfigField("String", "BUNDLE_BASE_URL", "\"https://github.com/LonglifeIO/FinePrint/releases/latest/download/\"")
        }
    }

    // Where the apps come from. device: this phone's, with the bundle downloaded (the app itself). preview: the
    // scan fixture's sample apps and a bundle built in (src/preview), a debug build to browse on any phone that
    // never reads its apps and has no network permission. Shared code names neither; each flavour's Flavour.kt does.
    flavorDimensions += "apps"
    productFlavors {
        create("device") { dimension = "apps"; isDefault = true }
        create("preview") { dimension = "apps"; applicationIdSuffix = ".preview" }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        compose = true
        buildConfig = true
    }

    sourceSets {
        // The instrumented tests render the real reviewed records, read from the test APK's assets.
        getByName("androidTest").assets.directories.add("../../bundle")
    }
    testOptions {
        // Robolectric needs the merged resources and assets: the screenshot tests draw real screens with real fonts.
        unitTests.isIncludeAndroidResources = true
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

/** Writes the debug network security config: cleartext only to the emulator host and an optional local host. */
abstract class DebugNetworkConfig : DefaultTask() {
    @get:Input abstract val extraHost: Property<String>
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun write() {
        val hosts = listOf("10.0.2.2") + extraHost.get().split(',').map { it.trim() }.filter { it.isNotEmpty() }
        val domains = hosts.joinToString("\n") { "        <domain includeSubdomains=\"false\">$it</domain>" }
        val file = outputDir.get().file("xml/network_security_config.xml").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |<?xml version="1.0" encoding="utf-8"?>
            |<!-- Generated by the debugNetworkConfig task; do not edit. -->
            |<network-security-config>
            |    <base-config cleartextTrafficPermitted="false" />
            |    <domain-config cleartextTrafficPermitted="true">
            |$domains
            |    </domain-config>
            |</network-security-config>
            |""".trimMargin(),
        )
    }
}

val debugNetworkConfig = tasks.register<DebugNetworkConfig>("debugNetworkConfig") {
    extraHost.set(debugCleartextHost)
    outputDir.set(layout.buildDirectory.dir("generated/networkConfig/res"))
}

/**
 * Copies the reviewed records into the debug build's assets at build time, for the G5 mockups'
 * @Previews. bundle/ stays the only copy in git; release builds get nothing from here.
 */
abstract class DebugBundleAssets : DefaultTask() {
    @get:InputFiles @get:PathSensitive(PathSensitivity.NAME_ONLY) abstract val records: ConfigurableFileCollection
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun copy() {
        val out = outputDir.get().asFile
        out.deleteRecursively()
        out.mkdirs()
        records.files.forEach { it.copyTo(File(out, it.name)) }
    }
}

val debugBundleAssets = tasks.register<DebugBundleAssets>("debugBundleAssets") {
    records.from("../../bundle/bundle.json", "../../bundle/jurisdictions.json")
    outputDir.set(layout.buildDirectory.dir("generated/bundleAssets"))
}

/**
 * The preview's sample apps and built-in bundle, copied into its assets (assets/preview/) at build time: the scan
 * fixture the tests use and the bundle's three files. Generated, so never in git; no other build gets them.
 */
abstract class PreviewAssets : DefaultTask() {
    @get:InputFiles @get:PathSensitive(PathSensitivity.NAME_ONLY) abstract val files: ConfigurableFileCollection
    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun copy() {
        val out = outputDir.get().asFile
        out.deleteRecursively()
        files.files.forEach { it.copyTo(File(out, "preview/${it.name}")) }
    }
}

val previewAssets = tasks.register<PreviewAssets>("previewAssets") {
    files.from("src/debug/assets/scan-fixture.json", "../../bundle/bundle.json", "../../bundle/trackers.json", "../../bundle/jurisdictions.json")
    outputDir.set(layout.buildDirectory.dir("generated/previewAssets"))
}

androidComponents {
    beforeVariants(selector().withFlavor("apps" to "preview")) { variant ->
        variant.enable = variant.buildType == "debug" // there is no preview release
        variant.deviceTests[DeviceTestBuilder.ANDROID_TEST_TYPE]?.enable = false // the device tests run on the device flavour
    }
    onVariants(selector().withBuildType("debug")) { variant ->
        variant.sources.res?.addGeneratedSourceDirectory(debugNetworkConfig, DebugNetworkConfig::outputDir)
    }
    onVariants(selector().withBuildType("debug").withFlavor("apps" to "device")) { variant ->
        variant.sources.assets?.addGeneratedSourceDirectory(debugBundleAssets, DebugBundleAssets::outputDir)
    }
    onVariants(selector().withFlavor("apps" to "preview")) { variant ->
        variant.sources.assets?.addGeneratedSourceDirectory(previewAssets, PreviewAssets::outputDir)
    }
}

dependencies {
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.compose.material3)
    // Reads dex files on-device. Apache 2.0; the only non-AndroidX runtime dependency.
    implementation(libs.smali.dexlib2) {
        // Declared by dexlib2 3.0.10 but never used by it: none of its classes reference Guava.
        exclude(group = "com.google.guava", module = "guava")
    }

    testImplementation(libs.junit)
    // Instrumented UI tests (TapTargetTest). Test-only, AndroidX; nothing here ships in the app.
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    // Compose's test library pulls in Espresso 3.5, which can't drive Android 17 (InputManager.getInstance is gone).
    androidTestImplementation(libs.androidx.test.espresso.core)
    debugImplementation(libs.androidx.compose.ui.test.manifest)
    // G5 mockups: @Preview and the preview renderer, debug builds only; checkReleaseClasspath keeps them out of release.
    debugImplementation(libs.androidx.compose.ui.tooling.preview)
    debugImplementation(libs.androidx.compose.ui.tooling)
    // Real org.json for JVM unit tests (android.jar only has stubs).
    testImplementation(libs.org.json)
    // Screenshot tests (G5 stop C): Robolectric draws the real screens on the JVM, Roborazzi saves them. Test-only.
    testImplementation(platform(libs.androidx.compose.bom))
    testImplementation(libs.robolectric)
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.androidx.compose.ui.test.junit4)
    // enableAccessibilityChecks() in the on-device tests (Accessibility Test Framework). Test-only.
    androidTestImplementation(libs.androidx.compose.ui.test.junit4.accessibility)
}

tasks.withType<Test>().configureEach {
    // Roborazzi saves every captureRoboImage call; the images land in build/outputs/roborazzi (an output, so the cache keeps them).
    systemProperty("roborazzi.test.record", "true")
    outputs.dir(layout.buildDirectory.dir("outputs/roborazzi"))
    // Robolectric's SDK 35+ sandbox reads FileDescriptor internals, which JDK 17+ keeps closed unless opened for tests.
    jvmArgs("--add-opens=java.base/jdk.internal.access=ALL-UNNAMED", "--add-exports=java.base/jdk.internal.access=ALL-UNNAMED")
    // The tests read the bundled signatures and bundle files from disk; rerun them when those change.
    inputs.file("src/main/assets/trackers.json").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir("src/test/resources").withPathSensitivity(PathSensitivity.RELATIVE).optional()
    // ...and the real bundle and the published method, which TierTest and MethodDocTest read.
    inputs.file("../../bundle/bundle.json").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file("../../bundle/jurisdictions.json").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file("../../docs/METHOD.md").withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file("src/main/assets/METHOD.md").withPathSensitivity(PathSensitivity.RELATIVE)
}

/**
 * Fails if any Compose tooling artefact (ui-tooling*, ui-test-manifest) is on the release runtime
 * classpath, or if any of the preview flavour reaches the release build: its classes (the preview package),
 * its assets (the sample apps and the built-in bundle) or its manifest. Debug builds may carry the tooling
 * for @Preview (CLAUDE.md, Conventions); release never does. Runs with `check`, before a release is
 * assembled, and in CI.
 */
abstract class CheckReleaseClasspath : DefaultTask() {
    @get:Input abstract val root: Property<ResolvedComponentResult>
    @get:InputFiles abstract val classJars: ListProperty<RegularFile>
    @get:InputFiles abstract val classDirs: ListProperty<Directory>
    @get:InputDirectory abstract val assets: DirectoryProperty
    @get:InputFile abstract val manifest: RegularFileProperty

    @TaskAction
    fun check() {
        val modules = mutableSetOf<String>()
        fun walk(component: ResolvedComponentResult) {
            for (dependency in component.dependencies) {
                if (dependency is ResolvedDependencyResult && modules.add(dependency.selected.id.displayName)) walk(dependency.selected)
            }
        }
        walk(root.get())
        val tooling = modules.filter { m -> listOf("androidx.compose.ui:ui-tooling", "androidx.compose.ui:ui-test-manifest").any { m.startsWith(it) } }
        if (tooling.isNotEmpty()) throw GradleException("Compose tooling on the release runtime classpath: ${tooling.sorted().joinToString()}")
        fun File.paths() = walk().filter { it.isFile }.map { it.relativeTo(this).invariantSeparatorsPath }.toList()
        val classes = classDirs.get().flatMap { it.asFile.paths() } + classJars.get().flatMap { ZipFile(it.asFile).use { z -> z.entries().toList().map { e -> e.name } } }
        val preview = classes.filter { it.startsWith("com/longlifeio/fineprint/preview/") } +
            assets.get().asFile.paths().filter { it.startsWith("preview/") || it == "scan-fixture.json" } +
            listOf("the preview's manifest").filter { "FinePrint preview" in manifest.get().asFile.readText() }
        if (preview.isNotEmpty()) throw GradleException("The preview flavour reaches the release build: ${preview.take(5).joinToString()}")
        logger.lifecycle("Release: ${modules.size} runtime modules, no Compose tooling; ${classes.size} class files and its assets and manifest, nothing of the preview.")
    }
}

val checkReleaseClasspath = tasks.register<CheckReleaseClasspath>("checkReleaseClasspath") {
    root.set(configurations.named("deviceReleaseRuntimeClasspath").flatMap { it.incoming.resolutionResult.rootComponent })
}
androidComponents {
    onVariants(selector().withBuildType("release")) { variant ->
        checkReleaseClasspath.configure {
            assets.set(variant.artifacts.get(SingleArtifact.ASSETS))
            manifest.set(variant.artifacts.get(SingleArtifact.MERGED_MANIFEST))
        }
        variant.artifacts.forScope(ScopedArtifacts.Scope.PROJECT).use(checkReleaseClasspath)
            .toGet(ScopedArtifact.CLASSES, CheckReleaseClasspath::classJars, CheckReleaseClasspath::classDirs)
    }
}
tasks.named("check") { dependsOn(checkReleaseClasspath) }
tasks.matching { it.name == "assembleDeviceRelease" || it.name == "bundleDeviceRelease" }.configureEach { dependsOn(checkReleaseClasspath) }

// The app itself is the device flavour; these keep the usual commands (CLAUDE.md, CI) as they were. testDebugUnitTest
// runs the full suite on the device flavour and the preview's own tests (src/testPreview) on the preview.
tasks.register("testDebugUnitTest") { group = "verification"; dependsOn("testDeviceDebugUnitTest", "testPreviewDebugUnitTest") }
tasks.register("connectedDebugAndroidTest") { group = "verification"; dependsOn("connectedDeviceDebugAndroidTest") }
tasks.withType<Test>().matching { it.name == "testPreviewDebugUnitTest" }.configureEach { filter.includeTestsMatching("com.longlifeio.fineprint.preview.*") }
// gradle.properties keeps the app installed after device tests; the test APK itself is removed.
tasks.matching { it.name == "connectedDeviceDebugAndroidTest" }.configureEach { finalizedBy("uninstallDeviceDebugAndroidTest") }

apply(from = "readme-screenshots.gradle.kts") // the README's screenshots (readmeScreenshots)
